import type { Cleaner } from "./types"

export const CLEANERS: Cleaner[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    avatar: "/cleaners/cleaner-1.png",
    tagline: "Your home, sparkling clean — every single time",
    location: "Brooklyn, NY",
    distance: "0.8 mi away",
    rating: 4.97,
    reviewCount: 312,
    hourlyRate: 38,
    minimumHours: 2,
    yearsExperience: 8,
    jobsCompleted: 1204,
    responseTime: "< 1 hr",
    availability: "Available Today",
    services: ["Deep Clean", "Regular Clean", "Move-in/out", "Eco-Friendly"],
    bio: "I take pride in delivering a thorough, meticulous clean every visit. I use eco-certified products and tailor each session to your home's needs.",
    verified: true,
    backgroundChecked: true,
    insured: true,
    languages: ["English", "Spanish"],
    badges: ["Top Rated", "Eco Certified", "1000+ Jobs"],
    featured: true,
    reviews: [
      {
        id: "r1",
        author: "Jennifer L.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=jennifer",
        rating: 5,
        date: "Jul 22, 2025",
        comment: "Sarah is an absolute gem! My apartment has never looked this spotless.",
      },
      {
        id: "r2",
        author: "Marcus T.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=marcus",
        rating: 5,
        date: "Jul 18, 2025",
        comment: "Extremely professional and thorough. I booked her weekly now.",
      },
    ],
  },
  {
    id: "2",
    name: "David Okafor",
    avatar: "/cleaners/cleaner-2.png",
    tagline: "Commercial & residential cleaning done right",
    location: "Manhattan, NY",
    distance: "1.2 mi away",
    rating: 4.89,
    reviewCount: 187,
    hourlyRate: 45,
    minimumHours: 3,
    yearsExperience: 12,
    jobsCompleted: 870,
    responseTime: "< 2 hrs",
    availability: "Available This Week",
    services: ["Office Clean", "Deep Clean", "Post-Construction", "Carpet Clean"],
    bio: "Specialist in commercial and post-construction cleaning with 12 years of experience. I handle large-scale jobs with a team or solo for smaller spaces.",
    verified: true,
    backgroundChecked: true,
    insured: true,
    languages: ["English", "French"],
    badges: ["Commercial Pro", "Background Checked", "Insured"],
    featured: false,
    reviews: [
      {
        id: "r3",
        author: "Lisa K.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=lisa",
        rating: 5,
        date: "Jul 20, 2025",
        comment: "David cleaned our office after renovation. Outstanding job!",
      },
      {
        id: "r4",
        author: "Robert M.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=robert",
        rating: 4,
        date: "Jul 10, 2025",
        comment: "Very reliable, great communication throughout.",
      },
    ],
  },
  {
    id: "3",
    name: "Amara Johnson",
    avatar: "/cleaners/cleaner-3.png",
    tagline: "Green cleaning for a healthier home",
    location: "Williamsburg, NY",
    distance: "2.1 mi away",
    rating: 4.95,
    reviewCount: 254,
    hourlyRate: 42,
    minimumHours: 2,
    yearsExperience: 6,
    jobsCompleted: 960,
    responseTime: "< 30 min",
    availability: "Available Today",
    services: ["Eco-Friendly", "Regular Clean", "Deep Clean", "Window Clean"],
    bio: "I specialize in non-toxic, plant-based cleaning solutions safe for kids, pets, and the environment. Quick to respond and highly flexible with scheduling.",
    verified: true,
    backgroundChecked: true,
    insured: false,
    languages: ["English"],
    badges: ["Eco Specialist", "Fast Responder", "Top Rated"],
    featured: true,
    reviews: [
      {
        id: "r5",
        author: "Tom W.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=tom",
        rating: 5,
        date: "Jul 25, 2025",
        comment: "Love that she uses eco products. The house smells so fresh and clean!",
      },
    ],
  },
  {
    id: "4",
    name: "Henry Brooks",
    avatar: "/cleaners/cleaner-4.png",
    tagline: "Reliable, experienced, and detail-focused",
    location: "Queens, NY",
    distance: "3.4 mi away",
    rating: 4.82,
    reviewCount: 143,
    hourlyRate: 34,
    minimumHours: 2,
    yearsExperience: 15,
    jobsCompleted: 620,
    responseTime: "< 3 hrs",
    availability: "Available Next Week",
    services: ["Regular Clean", "Move-in/out", "Carpet Clean"],
    bio: "With 15 years on the job, I've seen every kind of cleaning challenge and know how to tackle them all. Honest pricing and guaranteed satisfaction.",
    verified: true,
    backgroundChecked: true,
    insured: true,
    languages: ["English"],
    badges: ["15 Yrs Experience", "Background Checked", "Insured"],
    featured: false,
    reviews: [
      {
        id: "r6",
        author: "Carol B.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=carol",
        rating: 5,
        date: "Jul 12, 2025",
        comment: "Henry did our move-out clean and we got our full deposit back!",
      },
    ],
  },
  {
    id: "5",
    name: "Mei Lin",
    avatar: "/cleaners/cleaner-5.png",
    tagline: "Precision cleaning with a personal touch",
    location: "Flushing, NY",
    distance: "4.0 mi away",
    rating: 4.93,
    reviewCount: 198,
    hourlyRate: 40,
    minimumHours: 2,
    yearsExperience: 5,
    jobsCompleted: 730,
    responseTime: "< 1 hr",
    availability: "Available Today",
    services: ["Deep Clean", "Regular Clean", "Window Clean", "Eco-Friendly"],
    bio: "Detail-oriented and passionate about clean spaces. I bring my own supplies and ensure every corner of your home is perfectly cleaned.",
    verified: true,
    backgroundChecked: true,
    insured: true,
    languages: ["English", "Mandarin", "Cantonese"],
    badges: ["Multilingual", "Top Rated", "Insured"],
    featured: false,
    reviews: [
      {
        id: "r7",
        author: "Amy S.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=amy",
        rating: 5,
        date: "Jul 28, 2025",
        comment: "Mei is wonderful — she goes above and beyond every single time.",
      },
    ],
  },
  {
    id: "6",
    name: "Connor Walsh",
    avatar: "/cleaners/cleaner-6.png",
    tagline: "No-nonsense deep cleaning at fair prices",
    location: "Staten Island, NY",
    distance: "5.2 mi away",
    rating: 4.78,
    reviewCount: 96,
    hourlyRate: 30,
    minimumHours: 3,
    yearsExperience: 4,
    jobsCompleted: 310,
    responseTime: "< 2 hrs",
    availability: "Available This Week",
    services: ["Deep Clean", "Post-Construction", "Move-in/out"],
    bio: "Affordable rates with no compromise on quality. I specialize in heavy-duty deep cleaning projects and post-construction sites.",
    verified: true,
    backgroundChecked: false,
    insured: false,
    languages: ["English", "Irish"],
    badges: ["Budget Friendly", "Deep Clean Pro"],
    featured: false,
    reviews: [
      {
        id: "r8",
        author: "Pat D.",
        avatar: "https://api.dicebear.com/7.x/thumbs/svg?seed=pat",
        rating: 4,
        date: "Jul 15, 2025",
        comment: "Great value for money. Will definitely hire again.",
      },
    ],
  },
]

export const SERVICE_OPTIONS = [
  "Deep Clean",
  "Regular Clean",
  "Move-in/out",
  "Post-Construction",
  "Office Clean",
  "Carpet Clean",
  "Window Clean",
  "Eco-Friendly",
] as const

export const SORT_OPTIONS = [
  { value: "featured", label: "Featured" },
  { value: "rating", label: "Highest Rated" },
  { value: "price_low", label: "Price: Low to High" },
  { value: "price_high", label: "Price: High to Low" },
  { value: "reviews", label: "Most Reviews" },
  { value: "experience", label: "Most Experienced" },
] as const

export const AVAILABILITY_OPTIONS = [
  "Available Today",
  "Available This Week",
  "Available Next Week",
] as const
