"use client"

import { useEffect, useMemo, useState } from "react"
import Image from "next/image"
import { ArrowLeft, Bath, BedDouble, Building2, CalendarDays, Camera, Check, CheckCircle2, ChevronRight, Clock3, Home, Minus, PawPrint, Plus, ShieldCheck, Sparkles, Upload, X } from "lucide-react"
import type { Cleaner } from "@/lib/types"
import { ADD_ONS, AREAS, formatBookingDate, formatMoney, INITIAL_BOOKING, LAST_CLEANED, priceBooking, recommendHours, TIME_WINDOWS, type BookingDraft, type BookingService, type HomeType, type VisitType } from "@/lib/booking"
import { cn } from "@/lib/utils"
import { FieldLabel, SelectCard, StepTitle, TagButton } from "./BookingControls"
import { StarRating } from "../cleaners/StarRating"

const STEP_NAMES = ["Your clean", "Estimate", "Schedule", "Review"]
const PHOTO_COLORS = ["bg-accent", "bg-muted", "bg-secondary"]

function SummaryCard({ cleaner, draft }: { cleaner: Cleaner; draft: BookingDraft }) {
  const price = priceBooking(draft.hours, cleaner.hourlyRate)
  return <aside className="rounded-2xl border border-border bg-muted/40 p-4">
    <div className="flex items-center gap-3"><Image src={cleaner.avatar} alt="" width={42} height={42} className="size-11 rounded-xl object-cover" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-foreground">{cleaner.name}</p><StarRating rating={cleaner.rating} /></div></div>
    <div className="my-4 border-t border-border" />
    <dl className="flex flex-col gap-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">{draft.hours} hours × {formatMoney(cleaner.hourlyRate)}</dt><dd className="font-medium text-foreground">{formatMoney(price.labor)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Service fee (15%)</dt><dd className="font-medium text-foreground">{formatMoney(price.fee)}</dd></div><div className="mt-1 flex justify-between gap-3 border-t border-border pt-3"><dt className="font-semibold text-foreground">Estimated total</dt><dd className="text-lg font-bold text-foreground">{formatMoney(price.total)}</dd></div></dl>
    <p className="mt-3 flex items-start gap-2 text-xs leading-relaxed text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" />You won&apos;t be charged until the cleaner accepts.</p>
  </aside>
}

export function BookingFlow({ cleaner, onClose }: { cleaner: Cleaner; onClose: () => void }) {
  const [step, setStep] = useState(0)
  const [draft, setDraft] = useState<BookingDraft>(INITIAL_BOOKING)
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState("")
  const recommended = useMemo(() => recommendHours(draft), [draft])
  const price = priceBooking(draft.hours, cleaner.hourlyRate)
  const update = <K extends keyof BookingDraft>(key: K, value: BookingDraft[K]) => setDraft((current) => ({ ...current, [key]: value }))
  const toggle = (key: "areas" | "addOns", value: string) => update(key, draft[key].includes(value) ? draft[key].filter((item) => item !== value) : [...draft[key], value])

  useEffect(() => {
    document.body.style.overflow = "hidden"
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose() }
    window.addEventListener("keydown", closeOnEscape)
    return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", closeOnEscape) }
  }, [onClose])

  const goNext = () => {
    if (step === 0 && draft.areas.length === 0) return setError("Choose at least one area to clean.")
    if (step === 2 && (!draft.address || !draft.city || !draft.zip || !draft.date || !draft.timeWindow)) return setError("Add your full address, date, and preferred arrival window.")
    setError("")
    if (step === 0) update("hours", recommended)
    setStep((current) => Math.min(3, current + 1))
  }

  if (submitted) return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-foreground/50 p-0 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true" aria-labelledby="confirmed-title"><div className="flex h-full w-full flex-col overflow-y-auto bg-card sm:h-auto sm:max-h-[90vh] sm:max-w-2xl sm:rounded-3xl sm:border sm:border-border sm:shadow-2xl"><div className="p-6 sm:p-10"><button type="button" onClick={onClose} aria-label="Close confirmation" className="ml-auto flex size-9 items-center justify-center rounded-full border border-border text-muted-foreground hover:bg-muted"><X className="size-4" /></button><div className="mx-auto mt-4 flex max-w-lg flex-col items-center text-center"><span className="flex size-16 items-center justify-center rounded-2xl bg-accent text-accent-foreground"><CheckCircle2 className="size-8" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-primary">Request SF-{cleaner.id.toUpperCase()}42</p><h2 id="confirmed-title" className="mt-2 text-3xl font-bold text-foreground text-balance">Your request is on its way</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{cleaner.name} will review the details and usually responds within {cleaner.responseTime}. This request is pending until they accept.</p></div><div className="mx-auto mt-7 grid max-w-lg gap-3 rounded-2xl border border-border bg-muted/40 p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">When</p><p className="mt-1 text-sm font-semibold text-foreground">{formatBookingDate(draft.date)}</p><p className="text-xs text-muted-foreground">{draft.timeWindow} arrival</p></div><div><p className="text-xs text-muted-foreground">Where</p><p className="mt-1 text-sm font-semibold text-foreground">{draft.address}{draft.unit ? `, ${draft.unit}` : ""}</p><p className="text-xs text-muted-foreground">{draft.city}, {draft.zip}</p></div><div><p className="text-xs text-muted-foreground">Cleaning plan</p><p className="mt-1 text-sm font-semibold text-foreground">{draft.serviceType} · {draft.hours} hours</p><p className="text-xs text-muted-foreground">{draft.areas.length} areas, {draft.addOns.length} add-ons</p></div><div><p className="text-xs text-muted-foreground">Estimated total</p><p className="mt-1 text-lg font-bold text-foreground">{formatMoney(price.total)}</p><p className="text-xs text-muted-foreground">Includes 15% service fee</p></div></div><button onClick={onClose} className="mx-auto mt-6 block rounded-xl bg-primary px-7 py-3 text-sm font-semibold text-primary-foreground">Done</button></div></div></div>

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center bg-foreground/50 p-0 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true" aria-labelledby="booking-title">
      <div className="flex h-full w-full max-w-6xl flex-col overflow-hidden bg-card sm:h-[min(92vh,850px)] sm:rounded-3xl sm:border sm:border-border sm:shadow-2xl">
        <header className="flex items-center justify-between border-b border-border px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></span><div><p id="booking-title" className="text-sm font-semibold text-foreground">Request {cleaner.name}</p><p className="text-xs text-muted-foreground">No charge until accepted</p></div></div><button type="button" onClick={onClose} aria-label="Close booking" className="flex size-9 items-center justify-center rounded-full border border-border text-muted-foreground hover:bg-muted"><X className="size-4" /></button></header>
        <nav aria-label="Booking progress" className="border-b border-border px-4 py-3 sm:px-6"><ol className="mx-auto flex max-w-3xl items-center">{STEP_NAMES.map((name, index) => <li key={name} className={cn("flex items-center", index < STEP_NAMES.length - 1 && "flex-1")}><span className="flex items-center gap-2"><span className={cn("flex size-6 items-center justify-center rounded-full text-xs font-bold", index <= step ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}>{index < step ? <Check className="size-3.5" /> : index + 1}</span><span className={cn("hidden text-xs font-medium sm:block", index <= step ? "text-foreground" : "text-muted-foreground")}>{name}</span></span>{index < STEP_NAMES.length - 1 && <span className={cn("mx-2 h-px flex-1", index < step ? "bg-primary" : "bg-border")} />}</li>)}</ol></nav>

        <div className="min-h-0 flex-1 overflow-y-auto">
          <div className="mx-auto grid max-w-6xl gap-7 p-5 sm:p-7 lg:grid-cols-[minmax(0,1fr)_270px]">
            <div className="min-w-0">
              {step === 0 && <DetailsStep draft={draft} update={update} toggle={toggle} />}
              {step === 1 && <EstimateStep draft={draft} recommended={recommended} hourlyRate={cleaner.hourlyRate} update={update} />}
              {step === 2 && <ScheduleStep draft={draft} update={update} />}
              {step === 3 && <ReviewStep cleaner={cleaner} draft={draft} />}
              {error && <p role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p>}
            </div>
            <div className="hidden lg:block"><div className="sticky top-0"><SummaryCard cleaner={cleaner} draft={draft} /></div></div>
          </div>
        </div>
        <footer className="border-t border-border bg-card px-4 py-3 sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><button type="button" onClick={() => step === 0 ? onClose() : setStep(step - 1)} className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-foreground hover:bg-muted"><ArrowLeft className="size-4" />{step === 0 ? "Cancel" : "Back"}</button><div className="flex items-center gap-4"><p className="hidden text-right sm:block"><span className="block text-xs text-muted-foreground">Estimated total</span><span className="text-sm font-bold text-foreground">{formatMoney(price.total)}</span></p><button type="button" onClick={() => step === 3 ? setSubmitted(true) : goNext()} className="flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:opacity-90">{step === 3 ? "Send request" : "Continue"}<ChevronRight className="size-4" /></button></div></div></footer>
      </div>
    </div>
  )
}

function DetailsStep({ draft, update, toggle }: { draft: BookingDraft; update: <K extends keyof BookingDraft>(key: K, value: BookingDraft[K]) => void; toggle: (key: "areas" | "addOns", value: string) => void }) {
  return <div><StepTitle eyebrow="Step 1 of 4" title="Tell us about your clean" description="A few details help us recommend enough time for a thoughtful, unrushed clean." />
    <div className="mt-7"><FieldLabel>Is this your first clean?</FieldLabel><div className="grid gap-3 sm:grid-cols-2">{(["First clean", "Recurring"] as VisitType[]).map((item) => <SelectCard key={item} selected={draft.visitType === item} title={item} description={item === "First clean" ? "A fresh start and fuller reset" : "Keep your home consistently clean"} icon={item === "First clean" ? Sparkles : CalendarDays} onClick={() => update("visitType", item)} />)}</div></div>
    <div className="mt-6"><FieldLabel>Choose a service</FieldLabel><div className="grid gap-3 sm:grid-cols-3">{(["Standard", "Deep clean", "Move in/out"] as BookingService[]).map((item) => <SelectCard key={item} selected={draft.serviceType === item} title={item} description={item === "Standard" ? "Routine upkeep" : item === "Deep clean" ? "Extra detail & buildup" : "An empty-home reset"} onClick={() => update("serviceType", item)} />)}</div></div>
    <div className="mt-6"><FieldLabel>What kind of home?</FieldLabel><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(["Apartment", "House", "Townhouse", "Studio"] as HomeType[]).map((item) => <SelectCard key={item} selected={draft.homeType === item} title={item} icon={item === "Apartment" ? Building2 : Home} onClick={() => update("homeType", item)} />)}</div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">{[["Bedrooms", "bedrooms", BedDouble], ["Bathrooms", "bathrooms", Bath]].map(([label, key, Icon]) => <div key={key as string} className="flex items-center justify-between rounded-xl border border-border p-4"><div className="flex items-center gap-3"><Icon className="size-5 text-primary" /><span className="text-sm font-semibold text-foreground">{label as string}</span></div><div className="flex items-center gap-3"><button aria-label={`Decrease ${label}`} onClick={() => update(key as "bedrooms" | "bathrooms", Math.max(key === "bedrooms" ? 0 : 1, draft[key as "bedrooms" | "bathrooms"] - 1))} className="flex size-8 items-center justify-center rounded-full border border-border"><Minus className="size-3" /></button><span className="w-5 text-center text-sm font-bold">{draft[key as "bedrooms" | "bathrooms"]}</span><button aria-label={`Increase ${label}`} onClick={() => update(key as "bedrooms" | "bathrooms", draft[key as "bedrooms" | "bathrooms"] + 1)} className="flex size-8 items-center justify-center rounded-full border border-border"><Plus className="size-3" /></button></div></div>)}</div>
    <div className="mt-6"><FieldLabel>Areas to clean</FieldLabel><div className="flex flex-wrap gap-2">{AREAS.map((item) => <TagButton key={item} selected={draft.areas.includes(item)} onClick={() => toggle("areas", item)}>{item}</TagButton>)}</div></div>
    <div className="mt-6 grid gap-5 sm:grid-cols-2"><div><FieldLabel>When was it last professionally cleaned?</FieldLabel><select value={draft.lastCleaned} onChange={(event) => update("lastCleaned", event.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-3 text-sm text-foreground">{LAST_CLEANED.map((item) => <option key={item}>{item}</option>)}</select></div><div><FieldLabel>Pet hair?</FieldLabel><button type="button" onClick={() => update("petHair", !draft.petHair)} className={cn("flex w-full items-center justify-between rounded-xl border p-3 text-sm font-medium", draft.petHair ? "border-primary bg-accent" : "border-border")}><span className="flex items-center gap-2"><PawPrint className="size-4 text-primary" />{draft.petHair ? "Yes, please account for it" : "No pet hair"}</span>{draft.petHair && <Check className="size-4 text-primary" />}</button></div></div>
    <div className="mt-6"><FieldLabel>Add-on tasks</FieldLabel><div className="flex flex-wrap gap-2">{ADD_ONS.map((item) => <TagButton key={item} selected={draft.addOns.includes(item)} onClick={() => toggle("addOns", item)}>{item}</TagButton>)}</div></div>
    <div className="mt-6"><label htmlFor="requests" className="text-sm font-semibold text-foreground">Special requests</label><textarea id="requests" value={draft.specialRequests} onChange={(event) => update("specialRequests", event.target.value)} placeholder="Entry instructions, delicate surfaces, priorities, or anything else..." rows={4} className="mt-2 w-full resize-none rounded-xl border border-input bg-background p-3 text-sm text-foreground placeholder:text-muted-foreground" /></div>
  </div>
}

function EstimateStep({ draft, recommended, hourlyRate, update }: { draft: BookingDraft; recommended: number; hourlyRate: number; update: <K extends keyof BookingDraft>(key: K, value: BookingDraft[K]) => void }) {
  const price = priceBooking(draft.hours, hourlyRate)
  return <div><StepTitle eyebrow="Step 2 of 4" title="A practical estimate, upfront" description="We recommended a duration based on your home, service level, areas, condition, pets, and selected add-ons." /><div className="mt-7 rounded-2xl border border-primary/30 bg-accent p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent-foreground">Recommended</p><p className="mt-1 text-3xl font-bold text-foreground">{recommended} hours</p><p className="mt-1 text-sm text-muted-foreground">For a {draft.bedrooms}-bed, {draft.bathrooms}-bath {draft.homeType.toLowerCase()}</p></div><div className="flex items-center gap-4 rounded-xl bg-card p-2"><button aria-label="Reduce hours" onClick={() => update("hours", Math.max(2, draft.hours - 0.5))} className="flex size-10 items-center justify-center rounded-lg border border-border"><Minus className="size-4" /></button><div className="w-20 text-center"><p className="text-xl font-bold">{draft.hours}</p><p className="text-xs text-muted-foreground">hours</p></div><button aria-label="Add hours" onClick={() => update("hours", Math.min(12, draft.hours + 0.5))} className="flex size-10 items-center justify-center rounded-lg border border-border"><Plus className="size-4" /></button></div></div></div><div className="mt-6 rounded-2xl border border-border p-5"><h3 className="text-base font-semibold">Transparent price breakdown</h3><div className="mt-4 flex flex-col gap-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Cleaner time · {draft.hours}h × {formatMoney(hourlyRate)}</span><b>{formatMoney(price.labor)}</b></div><div className="flex justify-between"><span className="text-muted-foreground">SparkleFind service fee · 15%</span><b>{formatMoney(price.fee)}</b></div><div className="flex justify-between border-t border-border pt-4 text-base"><b>Estimated total</b><b>{formatMoney(price.total)}</b></div></div></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Your cleaner may suggest an adjustment after reviewing the request. Any change requires your approval before booking.</p></div>
}

function ScheduleStep({ draft, update }: { draft: BookingDraft; update: <K extends keyof BookingDraft>(key: K, value: BookingDraft[K]) => void }) {
  const addPhoto = () => update("photos", [...draft.photos, `Room ${draft.photos.length + 1}`].slice(0, 3))
  return <div><StepTitle eyebrow="Step 3 of 4" title="Show us the space and choose a time" description="Photos are optional in this prototype, but they help your cleaner prepare. Then add where and when you need them." /><div className="mt-7"><FieldLabel>Helpful photos <span className="font-normal text-muted-foreground">(optional)</span></FieldLabel><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{draft.photos.map((photo, index) => <div key={photo} className={cn("relative flex aspect-[4/3] items-center justify-center rounded-xl border border-border", PHOTO_COLORS[index])}><Camera className="size-7 text-muted-foreground" /><span className="absolute bottom-2 left-2 rounded-md bg-card/90 px-2 py-1 text-[10px] font-medium">{photo}</span><button aria-label={`Remove ${photo}`} onClick={() => update("photos", draft.photos.filter((item) => item !== photo))} className="absolute right-2 top-2 flex size-6 items-center justify-center rounded-full bg-card"><X className="size-3" /></button></div>)}{draft.photos.length < 3 && <button type="button" onClick={addPhoto} className="flex aspect-[4/3] flex-col items-center justify-center rounded-xl border border-dashed border-input text-muted-foreground hover:bg-muted"><Upload className="size-5" /><span className="mt-2 text-xs font-medium">Add dummy photo</span></button>}</div></div>
    <div className="mt-7"><FieldLabel>Service address</FieldLabel><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Street address" value={draft.address} onChange={(e) => update("address", e.target.value)} placeholder="Street address" className="rounded-xl border border-input bg-background px-3 py-3 text-sm sm:col-span-2" /><input aria-label="Apartment or unit" value={draft.unit} onChange={(e) => update("unit", e.target.value)} placeholder="Apartment / unit (optional)" className="rounded-xl border border-input bg-background px-3 py-3 text-sm" /><input aria-label="City" value={draft.city} onChange={(e) => update("city", e.target.value)} placeholder="City" className="rounded-xl border border-input bg-background px-3 py-3 text-sm" /><input aria-label="ZIP code" value={draft.zip} onChange={(e) => update("zip", e.target.value)} placeholder="ZIP code" inputMode="numeric" className="rounded-xl border border-input bg-background px-3 py-3 text-sm" /></div></div>
    <div className="mt-7"><FieldLabel>Preferred date</FieldLabel><input aria-label="Preferred date" type="date" min={new Date().toISOString().split("T")[0]} value={draft.date} onChange={(e) => update("date", e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-3 text-sm sm:w-72" /></div>
    <div className="mt-6"><FieldLabel>Arrival window</FieldLabel><div className="grid gap-3 sm:grid-cols-3">{TIME_WINDOWS.map((window) => <SelectCard key={window.value} selected={draft.timeWindow === window.value} title={window.value} description={window.time} icon={Clock3} onClick={() => update("timeWindow", window.value)} />)}</div></div>
  </div>
}

function ReviewStep({ cleaner, draft }: { cleaner: Cleaner; draft: BookingDraft }) {
  const rows = [["Service", `${draft.visitType} · ${draft.serviceType}`], ["Home", `${draft.homeType} · ${draft.bedrooms} bed · ${draft.bathrooms} bath`], ["Areas", draft.areas.join(", ")], ["Add-ons", draft.addOns.length ? draft.addOns.join(", ") : "None"], ["Duration", `${draft.hours} hours`], ["Date", `${formatBookingDate(draft.date)} · ${draft.timeWindow}`], ["Location", `${draft.address}${draft.unit ? `, ${draft.unit}` : ""}, ${draft.city} ${draft.zip}`], ["Photos", `${draft.photos.length} attached`]]
  return <div><StepTitle eyebrow="Step 4 of 4" title="Review your request" description={`Check the details before sending this request to ${cleaner.name}. Nothing is charged today.`} /><div className="mt-7 overflow-hidden rounded-2xl border border-border">{rows.map(([label, value]) => <div key={label} className="grid gap-1 border-b border-border px-4 py-3 last:border-0 sm:grid-cols-[120px_1fr]"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="text-sm font-medium text-foreground">{value}</p></div>)}</div>{draft.specialRequests && <div className="mt-4 rounded-2xl border border-border p-4"><p className="text-xs font-medium text-muted-foreground">Special requests</p><p className="mt-2 text-sm leading-relaxed text-foreground">{draft.specialRequests}</p></div>}<div className="mt-5 flex items-start gap-3 rounded-2xl bg-accent p-4"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="text-sm font-semibold text-foreground">A request, not an instant charge</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{cleaner.name} will confirm availability and can message you with questions. Payment is only authorized after acceptance.</p></div></div></div>
}
